name: Python application

on:
  schedule:
    - cron:  '30 12 * * *'  
  workflow_dispatch:
    inputs:
      manualrun:
        description: 'Manually run workflow'     
        required: true
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - uses: yaananth/run-notebook@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run notebook
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
        TWITTER_TOKEN_SECRET: ${{ secrets.TWITTER_TOKEN_SECRET }} 
      with:
        notebook: "vaccini.ipynb"
      run: |
          git status
